[project]
name = "django_safe_template_engine"
version = "1.1.0"
authors = [
  { name="Ronan Boiteau", email="ronan@boiteau.eu" },
]
description = "A Django template engine to render untrusted template code"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ronanboiteau/django_safe_template_engine"
"Bug Tracker" = "https://github.com/ronanboiteau/django_safe_template_engine/issues"
