version: 2.1

jobs:
  run_tests:
    resource_class: small
    working_directory: ~/safe_template_engine
    docker:
      - image: cimg/python:3.9.15
    steps:
      - checkout
      - restore_cache:
          key: dependencies-v1-{{ checksum "tests/requirements.txt" }}
      - run:
          name: "Install dependencies in a virtual environment"
          command: |
            python -m virtualenv ../venv
            source ../venv/bin/activate
            cd tests/
            python -m pip install -r requirements.txt
      - save_cache:
          key: dependencies-v1-{{ checksum "tests/requirements.txt" }}
          paths:
            - ../venv
      - run:
          name: "Validate ordering of Python imports with isort"
          command: |
            source ../venv/bin/activate
            isort --settings-path isort.cfg --check-only .
      - run:
          name: "Validate Python syntax with flake8"
          command: |
            source ../venv/bin/activate
            flake8 --config .flake8 .
      - run:
          name: Run tests
          command: |
            source ../venv/bin/activate
            python run_tests.py

workflows:
  workflow:
    jobs:
      - run_tests
