name: build
run-name: Workflow triggered by ${{ github.actor }}

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install tox
        run: pip install tox
      - name: Use tox to run test suite
        run: tox run
